[package]
name = "upstream-ontologist"
version = "0.1.35"
authors = [ "Jelmer Vernooij <jelmer@jelmer.uk>"]
edition = "2021"
license = "GPL-2.0+"
description = "tracking of upstream project metadata"
repository = "https://github.com/jelmer/upstream-ontologist.git"
homepage = "https://github.com/jelmer/upstream-ontologist"

[dependencies]
pyo3 = { workspace = true }
log = "0.4"
shlex = "1.1.0"
serde_json = "1.0"
reqwest = { version = "^0.11", features=["blocking", "json"], default-features = false }
lazy_static = "1"
regex = "1"
url = "2"
xmltree = "0.10"
configparser = "3"
rust-ini = { version = "0.19", optional = true }
serde_yaml = "0.8"
serde = { version = "1.0", features=["derive"]}
percent-encoding = "2"
opam-file-rs = { version = "0.1", optional = true }
gix-config = { version = ">=0.20", optional = true }
html5ever = ">=0.26"
distro-info = { version = "0.3", optional = true }
select = "0.6"
chrono = "0.4"
textwrap = ">=0.16"
toml = { version = ">=0.5", optional = true }
mailparse = { version = "0.14", optional = true }
pyproject-toml = { version = "0.6", optional = true }
python-pkginfo = { version = ">=0.5", optional = true }
lazy-regex = "2"
breezyshim = "0.1.24"

[workspace.dependencies]
pyo3 = "0.19"
pyo3-log = "0.8"

[features]
default = ["git-config", "launchpad", "opam", "dist-ini", "cargo", "r-description", "pyproject-toml", "python-pkginfo", "default-tls"]
default-tls = ["reqwest/default-tls"]
git-config = ["dep:gix-config"]
launchpad = ["dep:distro-info"]
opam = ["dep:opam-file-rs"]
dist-ini = ["dep:rust-ini"]
cargo = ["dep:toml"]
r-description = ["dep:mailparse"]
pyproject-toml = ["dep:pyproject-toml"]
python-pkginfo = ["dep:python-pkginfo"]
rustls-tls = ["reqwest/rustls-tls"]

[lib]

[workspace]
members = [ "upstream-ontologist-py" ]
