[package]
name = "upstream-ontologist"
version = "0.1.35"
authors = [ "Jelmer Vernooij <jelmer@jelmer.uk>"]
edition = "2021"
license = "GPL-2.0+"
description = "tracking of upstream project metadata"
repository = "https://github.com/jelmer/upstream-ontologist.git"
homepage = "https://github.com/jelmer/upstream-ontologist"

[dependencies]
pyo3 = { version = "0.18", features=["auto-initialize"]}
log = "0.4"
shlex = "1.1.0"
serde_json = "1.0"
reqwest = { version = "0.11", features=["blocking", "json"]}
lazy_static = "1"
regex = "1"
url = "2"
xmltree = "0.10"
configparser = "3"
rust-ini = "0.19"
serde_yaml = "0.8"
serde = { version = "1.0", features=["derive"]}
percent-encoding = "2"
opam-file-rs = { version = "0.1"}
gix-config = ">=0.20"
html5ever = ">=0.26"
distro-info = "0.3"
select = "0.6"
chrono = "0.4"
mailparse = "0.14"
textwrap = "0.11"

[lib]

[workspace]
members = [ "crates/*" ]
